# Generated by Django 6.1 on 2026-08-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("SMB", "SMB"),
                            ("Mid_market", "Mid-Market"),
                            ("Enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("signup_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductIncident",
            fields=[
                ("incident_id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("severity", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "subscription_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Pro", "Pro"),
                            ("Enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("status", models.CharField(max_length=20)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="agent_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("usage", models.IntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_usage",
                        to="agent_app.customer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["customer", "date"],
                        name="agent_app_d_custome_36f6ff_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "date"), name="unique_customer_usage_date"
                    )
                ],
            },
        ),
    ]
